import { Header } from "@/app/components/sections/Header";
import { Footer } from "@/app/components/sections/Footer";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/animations.css";
import "./styles/components.css";
import "./styles/beatProcrastination.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Habbits",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
      <html lang="en">
        <body
          className={`max-w-5xl mx-auto tracking-wide mb-4 ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap" rel="stylesheet" />
      
          <Header />
          <main className="flex-1">{children}</main>
          <Footer /> 
        </body>
      </html>
    );
  }